POST http://127.0.0.1:5000/auth/
Content-Type: application/json

{
  "username": "velali",
  "password": "qwerty",
  "role": "admin"
}
####

//{
//  "username": "Alina",
//  "password": "12345",
//  "role": "admin"
//}